# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"I\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\":\n\x16\x44\x65leteAllTodosResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\x11\x43reateTodoRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x1d\n\x0fMarkTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"J\n\x0cTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x04todo\x18\x03 \x01(\x0b\x32\n.todo.Todo\"-\n\x10GetTodosResponse\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo\"\x07\n\x05\x45mpty2\xb1\x02\n\x0bTodoService\x12\x39\n\nCreateTodo\x12\x17.todo.CreateTodoRequest\x1a\x12.todo.TodoResponse\x12/\n\x08GetTodos\x12\x0b.todo.Empty\x1a\x16.todo.GetTodosResponse\x12>\n\x11MarkTodoCompleted\x12\x15.todo.MarkTodoRequest\x1a\x12.todo.TodoResponse\x12\x39\n\nDeleteTodo\x12\x17.todo.DeleteTodoRequest\x1a\x12.todo.TodoResponse\x12;\n\x0e\x44\x65leteAllTodos\x12\x0b.todo.Empty\x1a\x1c.todo.DeleteAllTodosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODO']._serialized_start=20
  _globals['_TODO']._serialized_end=93
  _globals['_DELETEALLTODOSRESPONSE']._serialized_start=95
  _globals['_DELETEALLTODOSRESPONSE']._serialized_end=153
  _globals['_CREATETODOREQUEST']._serialized_start=155
  _globals['_CREATETODOREQUEST']._serialized_end=210
  _globals['_MARKTODOREQUEST']._serialized_start=212
  _globals['_MARKTODOREQUEST']._serialized_end=241
  _globals['_DELETETODOREQUEST']._serialized_start=243
  _globals['_DELETETODOREQUEST']._serialized_end=274
  _globals['_TODORESPONSE']._serialized_start=276
  _globals['_TODORESPONSE']._serialized_end=350
  _globals['_GETTODOSRESPONSE']._serialized_start=352
  _globals['_GETTODOSRESPONSE']._serialized_end=397
  _globals['_EMPTY']._serialized_start=399
  _globals['_EMPTY']._serialized_end=406
  _globals['_TODOSERVICE']._serialized_start=409
  _globals['_TODOSERVICE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
